### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by teccheck** [lcdr/raknet_shim_dll#2]
Hi, I'd like to build this code but the dependency "ring" fails building with this message: `error: failed to run custom build command for 'ring v0.13.5'`

I'm on Manjaro Linux with rustup on stable

**Comment by teccheck** [comment]
So zaop showed me the solution:

putting this into .cargo/config and installing `w64-mingw` will fix the problem
```toml
[build]
target = "i686-pc-windows-gnu"

[target.i686-pc-windows-gnu]
linker = "/usr/bin/i686-w64-mingw32-gcc"
rustflags = "-C panic=abort"
```
